version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pywebpush
    versions:
    - 1.12.0
  - dependency-name: alembic
    versions:
    - 1.5.6
  - dependency-name: cryptography
    versions:
    - 3.4.1
    - 3.4.4
    - 3.4.5
  rebase-strategy: disabled
