dist: bionic

language: python
python:
  - "3.8"

branches:
  only:
  - master
  - Dev

services:
  - postgresql

addons:
  postgresql: "12.2"

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database "test-capstone";' -U postgres

script:
  - coverage run test_app.py

after_success:
  - codecov
