dist: bionic

language: python
python:
  - "3.8"

branches:
  only:
  - master
  - Dev

before_install:
  - sudo pg_dropcluster --stop 12 main
  - sudo pg_upgradecluster 11 main
  - sudo pg_ctlcluster 12 main restart
  - sudo pg_dropcluster 11 main

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database "test-capstone";' -U postgres
  - pg_restore -d test-capstone capstone_db -Fc -c --no-owner

script:
  - coverage run test_app.py

after_success:
  - codecov
