dist: bionic

language: python
python:
  - "3.8"

branches:
  only:
  - master
  - Dev

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
  env:
    global:
        - PGPORT=5433

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database "test-capstone";' -U postgres

script:
  - coverage run test_app.py

after_success:
  - codecov
