CREATE DATABASE sendahug;

CREATE USER sah_api_user WITH ENCRYPTED PASSWORD '<INSERT_PW_HERE>' CREATEROLE;

GRANT ALL PRIVILEGES ON DATABASE sendahug TO sah_api_user;

\c sendahug
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sah_api_user;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO sah_api_user;

GRANT ALL ON SCHEMA public TO sah_api_user;
