version: 2.1
parameters:
  run_workflow_build:
    default: false
    type: boolean
orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  lint:
    docker:
      - image: cimg/python:3.10
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://postgres:password@localhost:5432/test_sah?sslmode=disable
    steps:
      - checkout
      - restore_cache:
          key: deps1-
      - run: pip3 install -r requirements.txt -r dev_requirements.txt
      - run: pre-commit install
      - save_cache:
          key: deps1-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/lib/python3.10/site-packages"
      - run: pre-commit run --all
      - run: mypy . --exclude 'migrations/' --check-untyped-defs
  build:
    docker:
      - image: cimg/python:3.10
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://postgres:password@localhost:5432/test_sah?sslmode=disable
      - image: cimg/postgres:14.10
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: test_sah
          POSTGRES_PASSWORD: "password"
    steps:
      - checkout
      - restore_cache:
          key: deps1-
      - run: sudo apt-get update
      - run: sudo apt-get install -y postgresql-client
      - run:
          name: Install Python deps
          command: |
            pip3 install -r requirements.txt -r dev_requirements.txt
            python3 -m pip install --upgrade pip
      # Dockerize installation to wait for the database to load
      # Taken from: https://support.circleci.com/hc/en-us/articles/360006773953-Race-Conditions-Wait-For-Database
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - save_cache:
          key: deps1-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/lib/python3.10/site-packages"
      - run:
          command: |
            pytest -x
      - codecov/upload

# Conditionally run testing depending on branch
# Once it's done, run codecov to upload test coverage
workflows:
  test:
    jobs:
      - lint
      - build
