"""empty message

Revision ID: 4822d58838df
Revises: fbd822a8ecd6
Create Date: 2020-05-30 12:13:14.593023

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "4822d58838df"
down_revision = "fbd822a8ecd6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("login_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "login_count")
    # ### end Alembic commands ###
