"""empty message

Revision ID: 028d27d5e5d0
Revises: e9aef1311cba
Create Date: 2020-07-08 12:06:20.974951

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "028d27d5e5d0"
down_revision = "e9aef1311cba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", sa.Integer(), nullable=False),
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.Column("subscription_data", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
