"""empty message

Revision ID: 9114f1efc30c
Revises:
Create Date: 2020-05-19 19:27:27.470711

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "9114f1efc30c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("auth0_id", sa.String(), nullable=False),
        sa.Column("received_hugs", sa.Integer(), nullable=True),
        sa.Column("given_hugs", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_id", sa.Integer(), nullable=False),
        sa.Column("for_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=480), nullable=False),
        sa.ForeignKeyConstraint(
            ["for_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["from_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=480), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts")
    op.drop_table("messages")
    op.drop_table("users")
    # ### end Alembic commands ###
