"""empty message

Revision ID: eb02c1ca03ec
Revises: 40d525bf350e
Create Date: 2020-06-23 16:24:12.195064

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "eb02c1ca03ec"
down_revision = "40d525bf350e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("for_deleted", sa.Boolean(), nullable=True))
    op.execute("UPDATE messages SET for_deleted = false;")
    op.alter_column("messages", "for_deleted", nullable=False)
    op.add_column("messages", sa.Column("from_deleted", sa.Boolean(), nullable=True))
    op.execute("UPDATE messages SET from_deleted = false;")
    op.alter_column("messages", "from_deleted", nullable=False)
    op.drop_column("messages", "user_1_deleted")
    op.drop_column("messages", "user_2_deleted")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column("user_2_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "messages",
        sa.Column("user_1_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("messages", "from_deleted")
    op.drop_column("messages", "for_deleted")
    # ### end Alembic commands ###
