"""empty message

Revision ID: 9c07afe43ee4
Revises: 1c6735c6ed2a
Create Date: 2020-07-20 17:17:13.703678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9c07afe43ee4"
down_revision = "1c6735c6ed2a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("sent_hugs", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "sent_hugs")
    # ### end Alembic commands ###
