"""empty message

Revision ID: 97ebcd9c039d
Revises: 9c07afe43ee4
Create Date: 2020-07-24 15:03:21.573754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ebcd9c039d'
down_revision = '9c07afe43ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_rate', sa.Integer(),
                                     nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_rate')
    # ### end Alembic commands ###
