"""empty message

Revision ID: 01fd6b9a8c9a
Revises: ee014068582b
Create Date: 2020-06-20 22:53:05.774218

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "01fd6b9a8c9a"
down_revision = "ee014068582b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=True),
        sa.Column("reporter", sa.Integer(), nullable=False),
        sa.Column("report_reason", sa.String(length=480), nullable=False),
        sa.Column("dismissed", sa.Boolean(), nullable=False),
        sa.Column("closed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reporter"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reports")
    # ### end Alembic commands ###
