"""empty message

Revision ID: 1c6735c6ed2a
Revises: 028d27d5e5d0
Create Date: 2020-07-09 15:16:40.252769

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "1c6735c6ed2a"
down_revision = "028d27d5e5d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("auto_refresh", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("push_enabled", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "push_enabled")
    op.drop_column("users", "auto_refresh")
    # ### end Alembic commands ###
