"""empty message

Revision ID: ee014068582b
Revises: 2a32dd21c76e
Create Date: 2020-06-14 13:00:51.679405

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ee014068582b"
down_revision = "2a32dd21c76e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "threads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_1_id", sa.Integer(), nullable=False),
        sa.Column("user_2_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_1_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_2_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("messages", sa.Column("thread", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "messages", "threads", ["thread"], ["id"])
    op.alter_column("messages", "thread", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_column("messages", "thread")
    op.drop_table("threads")
    # ### end Alembic commands ###
