"""empty message

Revision ID: e9aef1311cba
Revises: 1f97056a4575
Create Date: 2020-07-07 12:32:17.838176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e9aef1311cba"
down_revision = "1f97056a4575"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("for_id", sa.Integer(), nullable=False),
        sa.Column("from_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["for_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["from_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("hugs")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hugs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("for_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("from_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["for_id"], ["users.id"], name="hugs_for_id_fkey"),
        sa.ForeignKeyConstraint(["from_id"], ["users.id"], name="hugs_from_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="hugs_pkey"),
    )
    op.drop_table("notifications")
    # ### end Alembic commands ###
