"""Set proper cascade rules for delete/update

Revision ID: 812b00a075e3
Revises: d8921945f241
Create Date: 2023-02-12 12:31:42.604755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "812b00a075e3"
down_revision = "d8921945f241"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_constraint("messages_for_id_fkey", type_="foreignkey")
        batch_op.drop_constraint("messages_from_id_fkey", type_="foreignkey")
        batch_op.drop_constraint("messages_thread_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            "messages_for_id_fkey",
            "users",
            ["for_id"],
            ["id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            "messages_from_id_fkey",
            "users",
            ["from_id"],
            ["id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            "messages_thread_fkey",
            "threads",
            ["thread"],
            ["id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_constraint("notifications_from_id_fkey", type_="foreignkey")
        batch_op.drop_constraint("notifications_for_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            "notifications_from_id_fkey",
            "users",
            ["from_id"],
            ["id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            "notifications_for_id_fkey",
            "users",
            ["for_id"],
            ["id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_constraint("posts_user_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            "posts_user_id_fkey",
            "users",
            ["user_id"],
            ["id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        )

    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.alter_column(
            "report_reason",
            existing_type=sa.VARCHAR(length=480),
            type_=sa.String(length=120),
            existing_nullable=False,
        )
        batch_op.drop_constraint("reports_post_id_fkey", type_="foreignkey")
        batch_op.drop_constraint("reports_reporter_fkey", type_="foreignkey")
        batch_op.drop_constraint("reports_user_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            "reports_post_id_fkey",
            "posts",
            ["post_id"],
            ["id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            "reports_reporter_fkey",
            "users",
            ["reporter"],
            ["id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            "reports_user_id_fkey",
            "users",
            ["user_id"],
            ["id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        )

    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_constraint("subscriptions_user_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            "subscriptions_user_fkey",
            "users",
            ["user"],
            ["id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("threads", schema=None) as batch_op:
        batch_op.drop_constraint("threads_user_2_id_fkey", type_="foreignkey")
        batch_op.drop_constraint("threads_user_1_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            "threads_user_2_id_fkey",
            "users",
            ["user_2_id"],
            ["id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            "threads_user_1_id_fkey",
            "users",
            ["user_1_id"],
            ["id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("threads", schema=None) as batch_op:
        batch_op.drop_constraint("threads_user_1_id_fkey", type_="foreignkey")
        batch_op.drop_constraint("threads_user_2_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            "threads_user_1_id_fkey", "users", ["user_1_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "threads_user_2_id_fkey", "users", ["user_2_id"], ["id"]
        )

    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_constraint("subscriptions_user_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            "subscriptions_user_fkey", "users", ["user"], ["id"]
        )

    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_constraint("reports_user_id_fkey", type_="foreignkey")
        batch_op.drop_constraint("reports_reporter_fkey", type_="foreignkey")
        batch_op.drop_constraint("reports_post_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            "reports_user_id_fkey", "users", ["user_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "reports_reporter_fkey", "users", ["reporter"], ["id"]
        )
        batch_op.create_foreign_key(
            "reports_post_id_fkey", "posts", ["post_id"], ["id"]
        )
        batch_op.alter_column(
            "report_reason",
            existing_type=sa.String(length=120),
            type_=sa.VARCHAR(length=480),
            existing_nullable=False,
        )

    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_constraint("posts_user_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key("posts_user_id_fkey", "users", ["user_id"], ["id"])

    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_constraint("notifications_for_id_fkey", type_="foreignkey")
        batch_op.drop_constraint("notifications_from_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            "notifications_for_id_fkey", "users", ["for_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "notifications_from_id_fkey", "users", ["from_id"], ["id"]
        )

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_constraint("messages_thread_fkey", type_="foreignkey")
        batch_op.drop_constraint("messages_from_id_fkey", type_="foreignkey")
        batch_op.drop_constraint("messages_for_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            "messages_thread_fkey", "threads", ["thread"], ["id"]
        )
        batch_op.create_foreign_key(
            "messages_from_id_fkey", "users", ["from_id"], ["id"]
        )
        batch_op.create_foreign_key("messages_for_id_fkey", "users", ["for_id"], ["id"])

    # ### end Alembic commands ###
