"""deleted the old role column from the users table

Revision ID: 1d70342e9842
Revises: ca0fa484a1fa
Create Date: 2024-04-10 15:42:15.673774

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "1d70342e9842"
down_revision = "ca0fa484a1fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("role")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=True)
        )

    # ### end Alembic commands ###
