"""added tables for permissions and roles


Revision ID: ca0fa484a1fa
Revises: 75b20813c7e9
Create Date: 2024-04-10 14:33:52.057210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ca0fa484a1fa"
down_revision = "75b20813c7e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("permission", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roles_permissions_map",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    # Insert the roles and permissions from Auth0
    op.execute(
        """
        INSERT INTO permissions (permission, description) VALUES
        ('block:user', 'Block or unblock a user'),
        ('delete:any-post', 'Delete anyones post'),
        ('delete:messages', 'Delete my messages'),
        ('patch:any-post', 'Edit any post'),
        ('patch:any-user', 'Edit any users display name'),
        ('post:message', 'Create a new message'),
        ('post:post', 'Create a new post'),
        ('post:report', 'Create a new report.'),
        ('read:admin-board', 'View admin dashboard'),
        ('read:messages', 'Read user messages'),
        ('read:user', 'Read user data'),
        ('delete:my-post', 'Delete my own post'),
        ('patch:user', 'Edit user data'),
        ('patch:my-post', 'Edit my post'),
        ('post:user', 'Create a new user');
        """
    )
    op.execute(
        """
        INSERT INTO roles (name) VALUES ('admin'), ('moderator'),
        ('user'), ('new user');
        """
    )
    op.execute(
        """
        INSERT INTO roles_permissions_map (role_id, permission_id) VALUES
        (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9),
        (1, 10), (1, 11),
        (2, 3), (2, 12), (2, 4), (2, 13), (2, 6), (2, 7), (2, 8), (2, 10), (2, 11),
        (3, 3), (3, 12), (3, 14), (3, 13), (3, 6), (3, 7), (3, 8), (3, 10), (3, 11),
        (4, 3), (4, 12), (4, 14), (4, 13), (4, 6), (4, 7), (4, 15), (4, 10), (4, 11);
        """
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("role_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "users_role_id_fk",
            "roles",
            ["role_id"],
            ["id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        )
    op.execute(
        """
        UPDATE users SET role_id = CASE
            WHEN role = 'admin' THEN 1
            WHEN role = 'moderator' THEN 2
            WHEN role = 'user' THEN 3
            ELSE null
        END;
        """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("users_role_id_fk", type_="foreignkey")
        batch_op.drop_column("role_id")

    op.drop_table("roles_permissions_map")
    op.drop_table("roles")
    op.drop_table("permissions")
    # ### end Alembic commands ###
