"""added a verified column to the users table

Revision ID: eea8364baa35
Revises: 4314d062dce9
Create Date: 2024-09-18 11:52:13.721711

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "eea8364baa35"
down_revision = "4314d062dce9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email_verified", sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET email_verified = false;")
    op.alter_column("users", "email_verified", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_verified")
    # ### end Alembic commands ###
