"""Converted the sent_hugs column to an array

Revision ID: 75b20813c7e9
Revises: 812b00a075e3
Create Date: 2024-04-02 21:17:02.588673

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "75b20813c7e9"
down_revision = "812b00a075e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE posts ALTER COLUMN sent_hugs TYPE integer[] "
        "USING string_to_array(sent_hugs, ',')::int[]"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE posts ALTER COLUMN sent_hugs TYPE text "
        "USING array_to_string(sent_hugs, ',')::text"
    )
    # ### end Alembic commands ###
