"""added read column to notifications

Revision ID: 4314d062dce9
Revises: 9ac16223e62b
Create Date: 2024-08-11 13:30:01.008542

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "4314d062dce9"
down_revision = "9ac16223e62b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notifications", sa.Column("read", sa.Boolean(), nullable=True))
    op.execute("UPDATE notifications SET read = false;")
    op.alter_column("notifications", "read", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notifications", "read")
    # ### end Alembic commands ###
