"""Added a firebase_id column to the users table

Revision ID: 566bd4dfdf19
Revises: 7cffbe81fc6b
Create Date: 2024-04-29 19:16:53.950266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "566bd4dfdf19"
down_revision = "7cffbe81fc6b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("firebase_id", sa.String(length=50), nullable=True)
    )
    op.execute("UPDATE users SET firebase_id = 'undefined';")
    op.alter_column("users", "firebase_id", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "firebase_id")
    # ### end Alembic commands ###
