"""added read columns to the messages table

Revision ID: bb9bb49a5234
Revises: eea8364baa35
Create Date: 2024-10-25 21:00:15.085459

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "bb9bb49a5234"
down_revision = "eea8364baa35"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("from_read", sa.Boolean(), nullable=True))
    op.execute("UPDATE messages SET from_read = false;")
    op.alter_column("messages", "from_read", nullable=False)
    op.add_column("messages", sa.Column("for_read", sa.Boolean(), nullable=True))
    op.execute("UPDATE messages SET for_read = false;")
    op.alter_column("messages", "for_read", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "for_read")
    op.drop_column("messages", "from_read")
    # ### end Alembic commands ###
