"""Changed the hugs columns to be non-null

Revision ID: 7cffbe81fc6b
Revises: 1d70342e9842
Create Date: 2024-04-21 12:28:39.537102

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "7cffbe81fc6b"
down_revision = "1d70342e9842"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE posts SET given_hugs = 0 WHERE given_hugs IS NULL")
    op.alter_column("posts", "given_hugs", existing_type=sa.INTEGER(), nullable=False)
    op.execute("UPDATE users SET received_hugs = 0 WHERE received_hugs IS NULL")
    op.alter_column(
        "users", "received_hugs", existing_type=sa.INTEGER(), nullable=False
    )
    op.execute("UPDATE users SET given_hugs = 0 WHERE given_hugs IS NULL")
    op.alter_column("users", "given_hugs", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "given_hugs", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("users", "received_hugs", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("posts", "given_hugs", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
