"""added new profile fields and user preferences-related tables

Revision ID: 28f5ff010599
Revises: eea8364baa35
Create Date: 2024-12-11 14:58:51.728996

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "28f5ff010599"
down_revision = "eea8364baa35"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column(
            "selected_character",
            sa.Enum("KITTY", "BEAR", "DOG", name="usericoncharacter"),
            nullable=False,
        ),
        sa.Column("auto_refresh_enabled", sa.Boolean(), nullable=True),
        sa.Column("refresh_rate", sa.Integer(), nullable=True),
        sa.Column("push_enabled", sa.Boolean(), nullable=True),
        sa.Column("email_notifications_enabled", sa.Boolean(), nullable=True),
        sa.Column("message_notifications", sa.Boolean(), nullable=True),
        sa.Column("hugs_digest_notifications", sa.Boolean(), nullable=True),
        sa.Column("you_okay_notifications", sa.Boolean(), nullable=True),
        sa.Column("previous_interaction_notifications", sa.Boolean(), nullable=True),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.execute(
        """
        INSERT INTO user_preferences (
            user_id, selected_character, auto_refresh_enabled, refresh_rate,
            push_enabled, last_updated_at
        )
        SELECT id, CAST(UPPER(selected_character) AS usericoncharacter), auto_refresh,
        refresh_rate, push_enabled, current_timestamp
        FROM users;
        """
    )
    op.create_table(
        "users_icon_colours",
        sa.Column("user_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column(
            "icon_part",
            sa.Enum("CHARACTER", "LBG", "RBG", "ITEM", name="usericonpart"),
            nullable=False,
        ),
        sa.Column("colour", sa.String(length=7), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "icon_part"),
    )
    op.execute(
        """
        INSERT INTO users_icon_colours
        SELECT u.id, CAST(UPPER(j.key) AS usericonpart), j.value
        FROM users AS u
        JOIN json_each_text(CAST(u.icon_colours AS json)) AS j
        ON true;
        """
    )
    op.add_column("users", sa.Column("email", sa.String(length=75), nullable=True))
    op.execute("UPDATE users SET email = 'TEMP';")
    op.alter_column("users", "email", nullable=False)
    op.add_column("users", sa.Column("gender", sa.String(length=10), nullable=True))
    op.add_column(
        "users", sa.Column("platform_usage_reason", sa.String(length=25), nullable=True)
    )
    op.drop_column("users", "last_notifications_read")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "last_notifications_read",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("users", "platform_usage_reason")
    op.drop_column("users", "gender")
    op.drop_column("users", "email")
    op.drop_table("users_icon_colours")
    op.drop_table("user_preferences")
    op.execute("DROP TYPE usericoncharacter;")
    op.execute("DROP TYPE usericonpart;")
    # ### end Alembic commands ###
