"""Converted unneeded columns to column properties (expressions)

Revision ID: 9ac16223e62b
Revises: 8ccd78540d6b
Create Date: 2024-05-15 15:37:49.350862

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "9ac16223e62b"
down_revision = "8ccd78540d6b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "open_report")
    op.drop_column("threads", "user_2_deleted")
    op.drop_column("threads", "user_1_deleted")
    op.drop_column("users", "open_report")
    op.drop_column("users", "blocked")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("blocked", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("open_report", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.execute("UPDATE users SET blocked = false, open_report = false;")
    op.alter_column("users", "blocked", nullable=False)
    op.alter_column("users", "open_report", nullable=False)
    op.add_column(
        "threads",
        sa.Column("user_1_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "threads",
        sa.Column("user_2_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.execute("UPDATE threads SET user_1_deleted = false, user_2_deleted = false;")
    op.alter_column("threads", "user_1_deleted", nullable=False)
    op.alter_column("threads", "user_2_deleted", nullable=False)
    op.add_column(
        "posts",
        sa.Column("open_report", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.execute("UPDATE posts SET open_report = false;")
    op.alter_column("posts", "open_report", nullable=False)
    # ### end Alembic commands ###
