"""deleted the auth0 column and added unique constraint to firebase_id

Revision ID: 8ccd78540d6b
Revises: 566bd4dfdf19
Create Date: 2024-05-08 19:48:58.773376

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "8ccd78540d6b"
down_revision = "566bd4dfdf19"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "auth0_id")
    op.create_unique_constraint("firebase_id_uq", "users", ["firebase_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("auth0_id", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.execute("UPDATE users SET auth0_id = 'a'")
    op.alter_column("users", "auth0_id", nullable=True)
    op.drop_constraint("firebase_id_uq", "users", type_="unique")
    # ### end Alembic commands ###
