"""added archive column to posts table

Revision ID: be049055ffd7
Revises: 96df6db3b581
Create Date: 2025-08-08 11:11:51.444517

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "be049055ffd7"
down_revision = "96df6db3b581"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("archived", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "archived")
    # ### end Alembic commands ###
