"""changed the structure of the user settings

Revision ID: db38dcf8f5fe
Revises: 28f5ff010599
Create Date: 2025-01-20 19:04:19.585382

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "db38dcf8f5fe"
down_revision = "28f5ff010599"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("auto_refresh_enabled", sa.Boolean(), nullable=True),
        sa.Column("refresh_rate", sa.Integer(), nullable=True),
        sa.Column("push_enabled", sa.Boolean(), nullable=True),
        sa.Column("email_notifications_enabled", sa.Boolean(), nullable=True),
        sa.Column("message_notifications", sa.Boolean(), nullable=True),
        sa.Column("hugs_digest_notifications", sa.Boolean(), nullable=True),
        sa.Column("you_okay_notifications", sa.Boolean(), nullable=True),
        sa.Column("previous_interaction_notifications", sa.Boolean(), nullable=True),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.Column("gender", sa.String(length=10), nullable=True),
        sa.Column("platform_usage_reason", sa.String(length=25), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.execute(
        """
        INSERT INTO user_settings (user_id, auto_refresh_enabled, refresh_rate,
        push_enabled, email_notifications_enabled, message_notifications,
        hugs_digest_notifications, you_okay_notifications,
        previous_interaction_notifications, last_updated_at)
        SELECT user_id, auto_refresh_enabled, refresh_rate, push_enabled,
        email_notifications_enabled, message_notifications, hugs_digest_notifications,
        you_okay_notifications, previous_interaction_notifications, last_updated_at
        FROM user_preferences;
        """
    )
    op.drop_table("user_preferences")
    op.execute("UPDATE users SET selected_character = UPPER(selected_character);")
    op.alter_column(
        "users",
        "selected_character",
        existing_type=sa.VARCHAR(length=6),
        type_=sa.Enum("KITTY", "BEAR", "DOG", name="usericoncharacter"),
        nullable=False,
        postgresql_using="selected_character::usericoncharacter",
    )
    op.drop_column("users", "refresh_rate")
    op.drop_column("users", "icon_colours")
    op.drop_column("users", "auto_refresh")
    op.drop_column("users", "push_enabled")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("push_enabled", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("auto_refresh", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("icon_colours", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("refresh_rate", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "users",
        "selected_character",
        existing_type=sa.Enum("KITTY", "BEAR", "DOG", name="usericoncharacter"),
        type_=sa.VARCHAR(length=6),
        nullable=True,
    )
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "selected_character",
            postgresql.ENUM("KITTY", "BEAR", "DOG", name="usericoncharacter"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "auto_refresh_enabled", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column("refresh_rate", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("push_enabled", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "email_notifications_enabled",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "message_notifications", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "hugs_digest_notifications",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "you_okay_notifications", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "previous_interaction_notifications",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="user_preferences_user_id_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name="user_preferences_pkey"),
    )
    op.execute(
        """
        INSERT INTO user_preferences
        (user_id, selected_character, auto_refresh_enabled, refresh_rate, push_enabled,
        email_notifications_enabled, message_notifications, hugs_digest_notifications,
        you_okay_notifications, previous_interaction_notifications, last_updated_at)
        SELECT user_settings.user_id,
        CAST(user.selected_character AS usericoncharacter),
        user_settings.auto_refresh_enabled, user_settings.refresh_rate,
        user_settings.push_enabled, user_settings.email_notifications_enabled,
        user_settings.message_notifications, user_settings.hugs_digest_notifications,
        user_settings.you_okay_notifications,
        user_settings.previous_interaction_notifications, user_settings.last_updated_at
        FROM user_settings
        LEFT JOIN users ON users.id = user_settings.user_id;
        """
    )
    op.drop_table("user_settings")
    # ### end Alembic commands ###
