"""deleted the columns moved to the settings table

Revision ID: 96df6db3b581
Revises: db38dcf8f5fe
Create Date: 2025-01-20 19:58:04.556510

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "96df6db3b581"
down_revision = "db38dcf8f5fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "gender")
    op.drop_column("users", "platform_usage_reason")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "platform_usage_reason",
            sa.VARCHAR(length=25),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column("gender", sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
