# Trigger CircleCI build
name: Trigger Build

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ dev, staging, live ]
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

# Trigger CircleCI build via the API
jobs:
  curl:
    runs-on: ubuntu-latest
    container:
      image: python:3.9.1
    # If the PR is coming from a fork (pull_request_target), ensure it's opened by "dependabot[bot]".
    # Otherwise, clone it normally.
    # From here: https://hugo.alliau.me/2021/05/04/migration-to-github-native-dependabot-solutions-for-auto-merge-and-action-secrets/#share-your-secrets-with-dependabot
    if: |
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
    steps:
      - run: >-
            curl -X POST "https://circleci.com/api/v2/project/gh/sendahug/send-hug-backend/pipeline"
            --header 'Circle-Token: ${{ secrets.CIRCLE_CI_ACCESS_TOKEN }}'
            --header 'content-type: application/json'
            --header 'x-attribution-actor-id: ${{ github.actor }}'
            --header 'x-attribution-login: ${{ github.actor }}'
            --data '{"branch": "pull/${{ github.event.pull_request.number }}/head", "parameters":{"run_workflow_build":true}}'
