# Trigger CircleCI build
name: Trigger Build

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master, Dev ]

# Trigger CircleCI build via the API
jobs:
  curl:
    runs-on: ubuntu-latest
    container:
      image: python:3.9.1
    steps:
      - run: >- 
            curl -X POST "https://circleci.com/api/v2/project/gh/sendahug/send-hug-backend/pipeline"
            --header 'authorization: Circle-Token ${{ env.CIRCLE_CI_ACCESS_TOKEN }}'
            --header 'content-type: application/json'
            --header 'x-attribution-actor-id: ${{ github.actor }}'
            --header 'x-attribution-login: ${{ github.actor }}'
            --data '{"branch": ${{ github.head_ref }},"tag":"PR-CI"}' 
