# Trigger CircleCI build
name: Trigger Build

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master, Dev ]

# Trigger CircleCI build via the API
jobs:
  curl:
    runs-on: ubuntu-latest
    container:
      image: python:3.9.1
    steps:
      - run: |
          apk add curl
          apk add bash
      - name: curl -X POST \
            --url https://circleci.com/api/v2/project/gh/sendahug/send-hug-backend/pipeline \
            --header 'authorization:Circle-Token $CIRCLE_CI_ACCESS_TOKEN' \
            --header 'content-type:application/json' \
            --header 'x-attribution-actor-id:$GITHUB_ACTOR' \
            --header 'x-attribution-login:$GITHUB_ACTOR' \
            --data '{"branch":$GITHUB_HEAD_REF,"tag":"PR-CI"}' 
