name: Update Pre-Commit dependencies

on:
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   # run weekly on Monday 10am
  #   - cron:  '0 10 * * 1'
  push:
    branches: [fix/precommit_update]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.BOT_SSH_KEY }}

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit install

      - name: Update pre-commit dependencies
        run: pre-commit autoupdate

      - name: Commit & push changes
        run: |
          if [ -n "$(git status --porcelain)" ];
          then
            echo "updates_available=$((echo t))" >> $GITHUB_OUTPUT
            git config --global user.email "sendahugcom@gmail.com"
            git config --global user.name "Send A Hug Bot"
            git checkout -b 'deps/pre_commit_${{ github.run_id }}'
            git add .
            git commit -m 'deps: Bump Pre-Commit Dependencies'
            git push origin 'deps/pre_commit_${{ github.run_id }}'
          fi

      - run: echo ${{ steps.changelog-check.outputs.updates_available }}

      - uses: actions/github-script@v7
        if: steps.changelog-check.outputs.updates_available == 't'
        with:
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'deps: Update Pre-commit dependencies',
              head: 'deps/pre_commit_${{ github.run_id }}',
              base: 'dev'
            })
