name: Update Pre-Commit dependencies
permissions:
  actions: read
  contents: write
  pull-requests: write

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # run weekly on Monday 10am
    - cron:  '0 10 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v5
        with:
          ssh-key: ${{ secrets.BOT_SSH_KEY }}

      - uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit install

      - name: Update pre-commit dependencies
        run: pre-commit autoupdate

      - name: Commit & push changes
        id: commit-changes
        run: |
          if [ -n "$(git status --porcelain)" ];
          then
            echo "updates_available=t" >> $GITHUB_OUTPUT
            git config --global user.email "${{ secrets.BOT_EMAIL_ADDRESS }}"
            git config --global user.name "Send A Hug Bot"
            git checkout -b 'deps/pre_commit_${{ github.run_id }}'
            git add .
            git commit -m 'deps: Bump Pre-Commit Dependencies'
            git push origin 'deps/pre_commit_${{ github.run_id }}'
          fi

      - run: echo ${{ steps.commit-changes.outputs.updates_available }}

      - uses: actions/github-script@v7
        if: steps.commit-changes.outputs.updates_available == 't'
        with:
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'deps: Update Pre-commit dependencies',
              head: 'deps/pre_commit_${{ github.run_id }}',
              base: 'dev'
            })
